version: '3.6'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./db/postgre:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 --workers 4 --timeout=60 --thread 4 app:app
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - ENV=${ENV}
      - SECRET_KEY=${SECRET_KEY}
      - APP_CONFIG=${APP_CONFIG}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET_ID=${GITHUB_SECRET_ID}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_USER=${MAILGUN_USER}
      - DATABASE_URL=${DATABASE_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ID=${SENTRY_ID}
    depends_on:
      - db
